spring.application.name=SIMS

# [BARU] Render menyuntikkan env var PORT untuk web service. Kalau tidak ada
# (mis. saat run lokal), tetap pakai 8080 seperti sebelumnya.
server.port=${PORT:8080}

# Formatnya: ${NAMA_VARIABEL:nilai_default_untuk_lokal}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/db_sims}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# flyway ganti dari update ke validate
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
springdoc.api-docs.resolve-schema-properties=false

# biar akses backend jadi https
server.forward-headers-strategy=framework
# Membatasi maksimal ukuran satu file yang diupload menjadi 1MB
spring.servlet.multipart.max-file-size=1MB
# Membatasi maksimal ukuran total request (termasuk data form text lainnya) menjadi 1MB
spring.servlet.multipart.max-request-size=1MB